/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AAAARecordInitParameters struct {

	// Network to allocate an IP address from, when the 'ipv6_addr' field is empty (dynamic allocation). The address is in CIDR format. For static allocation, leave this field empty.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// Description of the AAAA-record.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// DNS view which the zone does exist within.
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// Extensible attributes of the AAAA-record to be added/updated, as a map in JSON format
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// The parent network block's extensible attributes (dynamic allocation). For static allocation, leave this field empty.
	FilterParams *string `json:"filterParams,omitempty" tf:"filter_params,omitempty"`

	// FQDN for the AAAA-record.
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	// IP address to associate with the AAAA-record. For static allocation, set the field with a valid IP address. For dynamic allocation, leave this field empty and set 'cidr' and 'network_view' fieldsor 'filter_params' and optional 'network_view' fields.
	IPv6Addr *string `json:"ipv6Addr,omitempty" tf:"ipv6_addr,omitempty"`

	// Network view to use when allocating an IP address from a network dynamically. For static allocation, leave this field empty.
	NetworkView *string `json:"networkView,omitempty" tf:"network_view,omitempty"`

	// TTL value for the AAAA-record.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type AAAARecordObservation struct {

	// Network to allocate an IP address from, when the 'ipv6_addr' field is empty (dynamic allocation). The address is in CIDR format. For static allocation, leave this field empty.
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// Description of the AAAA-record.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// DNS view which the zone does exist within.
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// Extensible attributes of the AAAA-record to be added/updated, as a map in JSON format
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// The parent network block's extensible attributes (dynamic allocation). For static allocation, leave this field empty.
	FilterParams *string `json:"filterParams,omitempty" tf:"filter_params,omitempty"`

	// FQDN for the AAAA-record.
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP address to associate with the AAAA-record. For static allocation, set the field with a valid IP address. For dynamic allocation, leave this field empty and set 'cidr' and 'network_view' fieldsor 'filter_params' and optional 'network_view' fields.
	IPv6Addr *string `json:"ipv6Addr,omitempty" tf:"ipv6_addr,omitempty"`

	InternalID *string `json:"internalId,omitempty" tf:"internal_id,omitempty"`

	// Network view to use when allocating an IP address from a network dynamically. For static allocation, leave this field empty.
	NetworkView *string `json:"networkView,omitempty" tf:"network_view,omitempty"`

	// NIOS object's reference, not to be set by a user.
	Ref *string `json:"ref,omitempty" tf:"ref,omitempty"`

	// TTL value for the AAAA-record.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type AAAARecordParameters struct {

	// Network to allocate an IP address from, when the 'ipv6_addr' field is empty (dynamic allocation). The address is in CIDR format. For static allocation, leave this field empty.
	// +kubebuilder:validation:Optional
	Cidr *string `json:"cidr,omitempty" tf:"cidr,omitempty"`

	// Description of the AAAA-record.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// DNS view which the zone does exist within.
	// +kubebuilder:validation:Optional
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// Extensible attributes of the AAAA-record to be added/updated, as a map in JSON format
	// +kubebuilder:validation:Optional
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// The parent network block's extensible attributes (dynamic allocation). For static allocation, leave this field empty.
	// +kubebuilder:validation:Optional
	FilterParams *string `json:"filterParams,omitempty" tf:"filter_params,omitempty"`

	// FQDN for the AAAA-record.
	// +kubebuilder:validation:Optional
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	// IP address to associate with the AAAA-record. For static allocation, set the field with a valid IP address. For dynamic allocation, leave this field empty and set 'cidr' and 'network_view' fieldsor 'filter_params' and optional 'network_view' fields.
	// +kubebuilder:validation:Optional
	IPv6Addr *string `json:"ipv6Addr,omitempty" tf:"ipv6_addr,omitempty"`

	// Network view to use when allocating an IP address from a network dynamically. For static allocation, leave this field empty.
	// +kubebuilder:validation:Optional
	NetworkView *string `json:"networkView,omitempty" tf:"network_view,omitempty"`

	// TTL value for the AAAA-record.
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

// AAAARecordSpec defines the desired state of AAAARecord
type AAAARecordSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AAAARecordParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AAAARecordInitParameters `json:"initProvider,omitempty"`
}

// AAAARecordStatus defines the observed state of AAAARecord.
type AAAARecordStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AAAARecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AAAARecord is the Schema for the AAAARecords API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infoblox-nios}
type AAAARecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fqdn) || (has(self.initProvider) && has(self.initProvider.fqdn))",message="spec.forProvider.fqdn is a required parameter"
	Spec   AAAARecordSpec   `json:"spec"`
	Status AAAARecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AAAARecordList contains a list of AAAARecords
type AAAARecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AAAARecord `json:"items"`
}

// Repository type metadata.
var (
	AAAARecord_Kind             = "AAAARecord"
	AAAARecord_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AAAARecord_Kind}.String()
	AAAARecord_KindAPIVersion   = AAAARecord_Kind + "." + CRDGroupVersion.String()
	AAAARecord_GroupVersionKind = CRDGroupVersion.WithKind(AAAARecord_Kind)
)

func init() {
	SchemeBuilder.Register(&AAAARecord{}, &AAAARecordList{})
}
