/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CNAMERecordInitParameters struct {

	// The alias name in FQDN format.
	Alias *string `json:"alias,omitempty" tf:"alias,omitempty"`

	// The Canonical name in FQDN format.
	Canonical *string `json:"canonical,omitempty" tf:"canonical,omitempty"`

	// A description about CNAME record.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Dns View under which the zone has been created.
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// The Extensible attributes of CNAME record, as a map in JSON format
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// TTL attribute value for the record.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type CNAMERecordObservation struct {

	// The alias name in FQDN format.
	Alias *string `json:"alias,omitempty" tf:"alias,omitempty"`

	// The Canonical name in FQDN format.
	Canonical *string `json:"canonical,omitempty" tf:"canonical,omitempty"`

	// A description about CNAME record.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Dns View under which the zone has been created.
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// The Extensible attributes of CNAME record, as a map in JSON format
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	InternalID *string `json:"internalId,omitempty" tf:"internal_id,omitempty"`

	// NIOS object's reference, not to be set by a user.
	Ref *string `json:"ref,omitempty" tf:"ref,omitempty"`

	// TTL attribute value for the record.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type CNAMERecordParameters struct {

	// The alias name in FQDN format.
	// +kubebuilder:validation:Optional
	Alias *string `json:"alias,omitempty" tf:"alias,omitempty"`

	// The Canonical name in FQDN format.
	// +kubebuilder:validation:Optional
	Canonical *string `json:"canonical,omitempty" tf:"canonical,omitempty"`

	// A description about CNAME record.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Dns View under which the zone has been created.
	// +kubebuilder:validation:Optional
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// The Extensible attributes of CNAME record, as a map in JSON format
	// +kubebuilder:validation:Optional
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// TTL attribute value for the record.
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

// CNAMERecordSpec defines the desired state of CNAMERecord
type CNAMERecordSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CNAMERecordParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CNAMERecordInitParameters `json:"initProvider,omitempty"`
}

// CNAMERecordStatus defines the observed state of CNAMERecord.
type CNAMERecordStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CNAMERecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CNAMERecord is the Schema for the CNAMERecords API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infoblox-nios}
type CNAMERecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.alias) || (has(self.initProvider) && has(self.initProvider.alias))",message="spec.forProvider.alias is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.canonical) || (has(self.initProvider) && has(self.initProvider.canonical))",message="spec.forProvider.canonical is a required parameter"
	Spec   CNAMERecordSpec   `json:"spec"`
	Status CNAMERecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CNAMERecordList contains a list of CNAMERecords
type CNAMERecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CNAMERecord `json:"items"`
}

// Repository type metadata.
var (
	CNAMERecord_Kind             = "CNAMERecord"
	CNAMERecord_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CNAMERecord_Kind}.String()
	CNAMERecord_KindAPIVersion   = CNAMERecord_Kind + "." + CRDGroupVersion.String()
	CNAMERecord_GroupVersionKind = CRDGroupVersion.WithKind(CNAMERecord_Kind)
)

func init() {
	SchemeBuilder.Register(&CNAMERecord{}, &CNAMERecordList{})
}
