/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AAAA) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *CNAME) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MX) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PTR) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Record) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SRV) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TXT) Hub() {}
