/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MXRecordInitParameters struct {

	// Description of the MX-Record.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// DNS view which the zone does exist within
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// Extensible attributes of the MX-record to be added/updated, as a map in JSON format.
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// FQDN for the MX-record.
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	// A record used to specify mail server.
	MailExchanger *string `json:"mailExchanger,omitempty" tf:"mail_exchanger,omitempty"`

	// Configures the preference (0-65535) for this MX-record.
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// TTL value for the MX-record.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type MXRecordObservation struct {

	// Description of the MX-Record.
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// DNS view which the zone does exist within
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// Extensible attributes of the MX-record to be added/updated, as a map in JSON format.
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// FQDN for the MX-record.
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	InternalID *string `json:"internalId,omitempty" tf:"internal_id,omitempty"`

	// A record used to specify mail server.
	MailExchanger *string `json:"mailExchanger,omitempty" tf:"mail_exchanger,omitempty"`

	// Configures the preference (0-65535) for this MX-record.
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// NIOS object's reference, not to be set by a user.
	Ref *string `json:"ref,omitempty" tf:"ref,omitempty"`

	// TTL value for the MX-record.
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

type MXRecordParameters struct {

	// Description of the MX-Record.
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// DNS view which the zone does exist within
	// +kubebuilder:validation:Optional
	DNSView *string `json:"dnsView,omitempty" tf:"dns_view,omitempty"`

	// Extensible attributes of the MX-record to be added/updated, as a map in JSON format.
	// +kubebuilder:validation:Optional
	ExtAttrs *string `json:"extAttrs,omitempty" tf:"ext_attrs,omitempty"`

	// FQDN for the MX-record.
	// +kubebuilder:validation:Optional
	Fqdn *string `json:"fqdn,omitempty" tf:"fqdn,omitempty"`

	// A record used to specify mail server.
	// +kubebuilder:validation:Optional
	MailExchanger *string `json:"mailExchanger,omitempty" tf:"mail_exchanger,omitempty"`

	// Configures the preference (0-65535) for this MX-record.
	// +kubebuilder:validation:Optional
	Preference *float64 `json:"preference,omitempty" tf:"preference,omitempty"`

	// TTL value for the MX-record.
	// +kubebuilder:validation:Optional
	TTL *float64 `json:"ttl,omitempty" tf:"ttl,omitempty"`
}

// MXRecordSpec defines the desired state of MXRecord
type MXRecordSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MXRecordParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MXRecordInitParameters `json:"initProvider,omitempty"`
}

// MXRecordStatus defines the observed state of MXRecord.
type MXRecordStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MXRecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MXRecord is the Schema for the MXRecords API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,infoblox-nios}
type MXRecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fqdn) || (has(self.initProvider) && has(self.initProvider.fqdn))",message="spec.forProvider.fqdn is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mailExchanger) || (has(self.initProvider) && has(self.initProvider.mailExchanger))",message="spec.forProvider.mailExchanger is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.preference) || (has(self.initProvider) && has(self.initProvider.preference))",message="spec.forProvider.preference is a required parameter"
	Spec   MXRecordSpec   `json:"spec"`
	Status MXRecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MXRecordList contains a list of MXRecords
type MXRecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MXRecord `json:"items"`
}

// Repository type metadata.
var (
	MXRecord_Kind             = "MXRecord"
	MXRecord_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MXRecord_Kind}.String()
	MXRecord_KindAPIVersion   = MXRecord_Kind + "." + CRDGroupVersion.String()
	MXRecord_GroupVersionKind = CRDGroupVersion.WithKind(MXRecord_Kind)
)

func init() {
	SchemeBuilder.Register(&MXRecord{}, &MXRecordList{})
}
